### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by jjdblast** [alvarouc/mlp#1]
It's a cool package ! But when I using Python2 and run this command:

`scores = cross_val_score(clf, data, label, cv=5, n_jobs=1, scoring='roc_auc')`

it's comes to an error:

> TypeError: super() takes at least 1 argument (0 given)

Maybe the usage of super are different in Python2 and Python3, I found some clues here:

[http://stackoverflow.com/questions/10838596/python-class-super-variable](url)

Hope for adjustment, or maybe this package designed for Python3 ?

**Comment by alvarouc** [comment]
Thanks, the package was developed for python3
