### ISSUE TITLE
Bug > ImportError: cannot import name 'l1l2'

### ISSUE THREAD

**Issue by devmessias** [alvarouc/mlp#5]
/usr/local/lib/python3.5/dist-packages/mlp/model.py in <module>()
      2 from keras.layers.core import Dense, Dropout
      3 from keras.optimizers import Adadelta, SGD, RMSprop, Adagrad, Adam, Adamax
----> 4 from keras.regularizers import l1l2
      5 from keras.callbacks import EarlyStopping, Callback
      6 from sklearn.model_selection import StratifiedShuffleSplit

ImportError: cannot import name 'l1l2'
keras version 1.2.2

**Comment by alvarouc** [comment]
thanks, I haven't updated this repo in a long time. Keras has changed the API significantly. I will try to get to this, but I can't promise a date. Feel free to contribute if you know the fix :)

**Comment by devmessias** [comment]
Next week I'll try fix. Thanks for mpl.

**Comment by haiantyz** [comment]
The l1l2 function in  keras has been changed to l1_l2, you can change this like  'from keras.regularizers import l1_l2' by yourself.

**Comment by ghost** [comment]
getting this same error
